[package]
name = "pkl_macros"
version = "0.1.1"
edition = "2021"
license = "Apache-2.0"
description = "Derive macro for pkl_core::PklDecode"
repository = "https://github.com/DevYatsu/pkl_bindgen.git"

[lib]
proc-macro = true

[dependencies]
syn = { version = "2", features = ["full"] }
quote = "1"
proc-macro2 = "1"
